### PR TITLE
major lake report updates

### PR DESCRIPTION
**Pull request by lindsaycarr**
Workflow:
1. Source the two functions: makeReports & renderLakeReport
2. Specify inputs to `makeReports`
3. Run `makeReports`
4. Repeat for other site numbers

```r
# for each site, call makeReports 
wy <- 2014
siteNumber <- '05390500'
reportNames <- c('ghtable', 'stagehydrograph')
makeReports(siteNumber, wy, reportNames, 'pdf')
```

Inputs for `makeReports` function
- `siteNumber` is the USGS station number as character
- `wy` is the water year as numeric
- `reportNames` is a character value or vector [options: `ghtable`, `stagehydrograph`, `qwtable`, `depthprofiles`, `qwtimeseries`]
- `output` is the format you would like the file saved as [options: `pdf`, `html`, `word`]

### CODE REVIEW

**Comment by jread-usgs** [comment]
:shipit:

**Comment by lindsaycarr** [comment]
@jread-usgs @ldecicco-USGS I don't have write access to this repo, so I can't merge it!

**Comment by ldecicco-USGS** [comment]
@lindsaycarr you should have write privileges now

**Comment by lindsaycarr** [comment]
thanks

**Pull request merged**
