### PR TITLE
re-organization 

### PR DESCRIPTION
**Pull request by lindsaycarr**

### CODE REVIEW

**Comment by lindsaycarr** [comment]
@ldecicco-USGS should we delete `workflow.R` and `workflow_min.R` or leave them in here? Also, what is the `TestReport.Rnw` file?

**Comment by ldecicco-USGS** [comment]
Delete all the things!

**Comment by ldecicco-USGS** [comment]
.Rnw was the first shot at creating the whole report via latex. Forget that.

**Comment by lindsaycarr** [comment]
Awesome thanks - glad I've never had to touch latex....looks very confusing/overwhelming/terrifying.

**Pull request merged**
